### ISSUE TITLE
Repo is missing file curation.png referenced in Makefile

### ISSUE THREAD

**Issue by rsav** [msdemlei/DocRegExt#1]
Reference in Makefile:
https://github.com/msdemlei/DocRegExt/blob/41049ccf14210b0f42581ba13ce7db430a25308a/Makefile#L22

I had to remove curation.png from FIGURES to compile DocRegExt.pdf with make

**Comment by msdemlei** [comment]
Fixed in 0ef83fab61157ab65f135e95f39146fb1638eee8
