### ISSUE TITLE
URL http://svn.ari.uni-heidelberg.de/svn/edu/README referenced in section B was not found on this server.

### ISSUE THREAD

**Issue by rsav** [msdemlei/DocRegExt#2]
Reference:

https://github.com/msdemlei/DocRegExt/blob/41049ccf14210b0f42581ba13ce7db430a25308a/DocRegExt.tex#L500

**Comment by msdemlei** [comment]
Fixed in 0ef83fab61157ab65f135e95f39146fb1638eee8
